// Autogenerated from Pigeon (v1.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTVersion;
@class FLTBattery;
@class FLTDrone;

@interface FLTVersion : NSObject
@property(nonatomic, copy, nullable) NSString * string;
@end

@interface FLTBattery : NSObject
@property(nonatomic, strong, nullable) NSNumber * level;
@end

@interface FLTDrone : NSObject
@property(nonatomic, copy, nullable) NSString * status;
@property(nonatomic, strong, nullable) NSNumber * batteryPercent;
@property(nonatomic, strong, nullable) NSNumber * altitude;
@property(nonatomic, strong, nullable) NSNumber * latitude;
@property(nonatomic, strong, nullable) NSNumber * longitude;
@property(nonatomic, strong, nullable) NSNumber * speed;
@property(nonatomic, strong, nullable) NSNumber * roll;
@property(nonatomic, strong, nullable) NSNumber * pitch;
@property(nonatomic, strong, nullable) NSNumber * yaw;
@end

/// The codec used by FLTDjiHostApi.
NSObject<FlutterMessageCodec> *FLTDjiHostApiGetCodec(void);

@protocol FLTDjiHostApi
- (nullable FLTVersion *)getPlatformVersionWithError:(FlutterError *_Nullable *_Nonnull)error;
- (nullable FLTBattery *)getBatteryLevelWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)registerAppWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)connectDroneWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)disconnectDroneWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)delegateDroneWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)takeOffWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)landWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)timelineWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)startFlightJson:(NSString *)flightJson error:(FlutterError *_Nullable *_Nonnull)error;
- (void)downloadAllMediaWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)deleteAllMediaWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTDjiHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTDjiHostApi> *_Nullable api);

/// The codec used by FLTDjiFlutterApi.
NSObject<FlutterMessageCodec> *FLTDjiFlutterApiGetCodec(void);

@interface FLTDjiFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)setStatusDrone:(FLTDrone *)drone completion:(void(^)(NSError *_Nullable))completion;
@end
NS_ASSUME_NONNULL_END
