// Autogenerated from Pigeon (v4.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "messages.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ?: [NSNull null]),
        @"message": (error.message ?: [NSNull null]),
        @"details": (error.details ?: [NSNull null]),
        };
  }
  return @{
      @"result": (result ?: [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}


@interface FLTVersion ()
+ (FLTVersion *)fromMap:(NSDictionary *)dict;
+ (nullable FLTVersion *)nullableFromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end
@interface FLTBattery ()
+ (FLTBattery *)fromMap:(NSDictionary *)dict;
+ (nullable FLTBattery *)nullableFromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end
@interface FLTDrone ()
+ (FLTDrone *)fromMap:(NSDictionary *)dict;
+ (nullable FLTDrone *)nullableFromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end
@interface FLTMedia ()
+ (FLTMedia *)fromMap:(NSDictionary *)dict;
+ (nullable FLTMedia *)nullableFromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end
@interface FLTStream ()
+ (FLTStream *)fromMap:(NSDictionary *)dict;
+ (nullable FLTStream *)nullableFromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation FLTVersion
+ (instancetype)makeWithString:(nullable NSString *)string {
  FLTVersion* pigeonResult = [[FLTVersion alloc] init];
  pigeonResult.string = string;
  return pigeonResult;
}
+ (FLTVersion *)fromMap:(NSDictionary *)dict {
  FLTVersion *pigeonResult = [[FLTVersion alloc] init];
  pigeonResult.string = GetNullableObject(dict, @"string");
  return pigeonResult;
}
+ (nullable FLTVersion *)nullableFromMap:(NSDictionary *)dict { return (dict) ? [FLTVersion fromMap:dict] : nil; }
- (NSDictionary *)toMap {
  return @{
    @"string" : (self.string ?: [NSNull null]),
  };
}
@end

@implementation FLTBattery
+ (instancetype)makeWithLevel:(nullable NSNumber *)level {
  FLTBattery* pigeonResult = [[FLTBattery alloc] init];
  pigeonResult.level = level;
  return pigeonResult;
}
+ (FLTBattery *)fromMap:(NSDictionary *)dict {
  FLTBattery *pigeonResult = [[FLTBattery alloc] init];
  pigeonResult.level = GetNullableObject(dict, @"level");
  return pigeonResult;
}
+ (nullable FLTBattery *)nullableFromMap:(NSDictionary *)dict { return (dict) ? [FLTBattery fromMap:dict] : nil; }
- (NSDictionary *)toMap {
  return @{
    @"level" : (self.level ?: [NSNull null]),
  };
}
@end

@implementation FLTDrone
+ (instancetype)makeWithStatus:(nullable NSString *)status
    error:(nullable NSString *)error
    batteryPercent:(nullable NSNumber *)batteryPercent
    altitude:(nullable NSNumber *)altitude
    latitude:(nullable NSNumber *)latitude
    longitude:(nullable NSNumber *)longitude
    speed:(nullable NSNumber *)speed
    roll:(nullable NSNumber *)roll
    pitch:(nullable NSNumber *)pitch
    yaw:(nullable NSNumber *)yaw {
  FLTDrone* pigeonResult = [[FLTDrone alloc] init];
  pigeonResult.status = status;
  pigeonResult.error = error;
  pigeonResult.batteryPercent = batteryPercent;
  pigeonResult.altitude = altitude;
  pigeonResult.latitude = latitude;
  pigeonResult.longitude = longitude;
  pigeonResult.speed = speed;
  pigeonResult.roll = roll;
  pigeonResult.pitch = pitch;
  pigeonResult.yaw = yaw;
  return pigeonResult;
}
+ (FLTDrone *)fromMap:(NSDictionary *)dict {
  FLTDrone *pigeonResult = [[FLTDrone alloc] init];
  pigeonResult.status = GetNullableObject(dict, @"status");
  pigeonResult.error = GetNullableObject(dict, @"error");
  pigeonResult.batteryPercent = GetNullableObject(dict, @"batteryPercent");
  pigeonResult.altitude = GetNullableObject(dict, @"altitude");
  pigeonResult.latitude = GetNullableObject(dict, @"latitude");
  pigeonResult.longitude = GetNullableObject(dict, @"longitude");
  pigeonResult.speed = GetNullableObject(dict, @"speed");
  pigeonResult.roll = GetNullableObject(dict, @"roll");
  pigeonResult.pitch = GetNullableObject(dict, @"pitch");
  pigeonResult.yaw = GetNullableObject(dict, @"yaw");
  return pigeonResult;
}
+ (nullable FLTDrone *)nullableFromMap:(NSDictionary *)dict { return (dict) ? [FLTDrone fromMap:dict] : nil; }
- (NSDictionary *)toMap {
  return @{
    @"status" : (self.status ?: [NSNull null]),
    @"error" : (self.error ?: [NSNull null]),
    @"batteryPercent" : (self.batteryPercent ?: [NSNull null]),
    @"altitude" : (self.altitude ?: [NSNull null]),
    @"latitude" : (self.latitude ?: [NSNull null]),
    @"longitude" : (self.longitude ?: [NSNull null]),
    @"speed" : (self.speed ?: [NSNull null]),
    @"roll" : (self.roll ?: [NSNull null]),
    @"pitch" : (self.pitch ?: [NSNull null]),
    @"yaw" : (self.yaw ?: [NSNull null]),
  };
}
@end

@implementation FLTMedia
+ (instancetype)makeWithFileName:(nullable NSString *)fileName
    fileUrl:(nullable NSString *)fileUrl
    fileIndex:(nullable NSNumber *)fileIndex {
  FLTMedia* pigeonResult = [[FLTMedia alloc] init];
  pigeonResult.fileName = fileName;
  pigeonResult.fileUrl = fileUrl;
  pigeonResult.fileIndex = fileIndex;
  return pigeonResult;
}
+ (FLTMedia *)fromMap:(NSDictionary *)dict {
  FLTMedia *pigeonResult = [[FLTMedia alloc] init];
  pigeonResult.fileName = GetNullableObject(dict, @"fileName");
  pigeonResult.fileUrl = GetNullableObject(dict, @"fileUrl");
  pigeonResult.fileIndex = GetNullableObject(dict, @"fileIndex");
  return pigeonResult;
}
+ (nullable FLTMedia *)nullableFromMap:(NSDictionary *)dict { return (dict) ? [FLTMedia fromMap:dict] : nil; }
- (NSDictionary *)toMap {
  return @{
    @"fileName" : (self.fileName ?: [NSNull null]),
    @"fileUrl" : (self.fileUrl ?: [NSNull null]),
    @"fileIndex" : (self.fileIndex ?: [NSNull null]),
  };
}
@end

@implementation FLTStream
+ (instancetype)makeWithData:(nullable FlutterStandardTypedData *)data {
  FLTStream* pigeonResult = [[FLTStream alloc] init];
  pigeonResult.data = data;
  return pigeonResult;
}
+ (FLTStream *)fromMap:(NSDictionary *)dict {
  FLTStream *pigeonResult = [[FLTStream alloc] init];
  pigeonResult.data = GetNullableObject(dict, @"data");
  return pigeonResult;
}
+ (nullable FLTStream *)nullableFromMap:(NSDictionary *)dict { return (dict) ? [FLTStream fromMap:dict] : nil; }
- (NSDictionary *)toMap {
  return @{
    @"data" : (self.data ?: [NSNull null]),
  };
}
@end

@interface FLTDjiHostApiCodecReader : FlutterStandardReader
@end
@implementation FLTDjiHostApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [FLTBattery fromMap:[self readValue]];
    
    case 129:     
      return [FLTMedia fromMap:[self readValue]];
    
    case 130:     
      return [FLTVersion fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface FLTDjiHostApiCodecWriter : FlutterStandardWriter
@end
@implementation FLTDjiHostApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[FLTBattery class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
  if ([value isKindOfClass:[FLTMedia class]]) {
    [self writeByte:129];
    [self writeValue:[value toMap]];
  } else 
  if ([value isKindOfClass:[FLTVersion class]]) {
    [self writeByte:130];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface FLTDjiHostApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FLTDjiHostApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FLTDjiHostApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FLTDjiHostApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FLTDjiHostApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    FLTDjiHostApiCodecReaderWriter *readerWriter = [[FLTDjiHostApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void FLTDjiHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTDjiHostApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.DjiHostApi.getPlatformVersion"
        binaryMessenger:binaryMessenger
        codec:FLTDjiHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getPlatformVersionWithError:)], @"FLTDjiHostApi api (%@) doesn't respond to @selector(getPlatformVersionWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        FLTVersion *output = [api getPlatformVersionWithError:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.DjiHostApi.getBatteryLevel"
        binaryMessenger:binaryMessenger
        codec:FLTDjiHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getBatteryLevelWithError:)], @"FLTDjiHostApi api (%@) doesn't respond to @selector(getBatteryLevelWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        FLTBattery *output = [api getBatteryLevelWithError:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.DjiHostApi.registerApp"
        binaryMessenger:binaryMessenger
        codec:FLTDjiHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(registerAppWithError:)], @"FLTDjiHostApi api (%@) doesn't respond to @selector(registerAppWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api registerAppWithError:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.DjiHostApi.connectDrone"
        binaryMessenger:binaryMessenger
        codec:FLTDjiHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(connectDroneWithError:)], @"FLTDjiHostApi api (%@) doesn't respond to @selector(connectDroneWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api connectDroneWithError:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.DjiHostApi.disconnectDrone"
        binaryMessenger:binaryMessenger
        codec:FLTDjiHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(disconnectDroneWithError:)], @"FLTDjiHostApi api (%@) doesn't respond to @selector(disconnectDroneWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api disconnectDroneWithError:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.DjiHostApi.delegateDrone"
        binaryMessenger:binaryMessenger
        codec:FLTDjiHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(delegateDroneWithError:)], @"FLTDjiHostApi api (%@) doesn't respond to @selector(delegateDroneWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api delegateDroneWithError:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.DjiHostApi.takeOff"
        binaryMessenger:binaryMessenger
        codec:FLTDjiHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(takeOffWithError:)], @"FLTDjiHostApi api (%@) doesn't respond to @selector(takeOffWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api takeOffWithError:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.DjiHostApi.land"
        binaryMessenger:binaryMessenger
        codec:FLTDjiHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(landWithError:)], @"FLTDjiHostApi api (%@) doesn't respond to @selector(landWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api landWithError:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.DjiHostApi.start"
        binaryMessenger:binaryMessenger
        codec:FLTDjiHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(startFlightJson:error:)], @"FLTDjiHostApi api (%@) doesn't respond to @selector(startFlightJson:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_flightJson = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api startFlightJson:arg_flightJson error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.DjiHostApi.mobileRemoteController"
        binaryMessenger:binaryMessenger
        codec:FLTDjiHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(mobileRemoteControllerEnabled:leftStickHorizontal:leftStickVertical:rightStickHorizontal:rightStickVertical:error:)], @"FLTDjiHostApi api (%@) doesn't respond to @selector(mobileRemoteControllerEnabled:leftStickHorizontal:leftStickVertical:rightStickHorizontal:rightStickVertical:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_enabled = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_leftStickHorizontal = GetNullableObjectAtIndex(args, 1);
        NSNumber *arg_leftStickVertical = GetNullableObjectAtIndex(args, 2);
        NSNumber *arg_rightStickHorizontal = GetNullableObjectAtIndex(args, 3);
        NSNumber *arg_rightStickVertical = GetNullableObjectAtIndex(args, 4);
        FlutterError *error;
        [api mobileRemoteControllerEnabled:arg_enabled leftStickHorizontal:arg_leftStickHorizontal leftStickVertical:arg_leftStickVertical rightStickHorizontal:arg_rightStickHorizontal rightStickVertical:arg_rightStickVertical error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.DjiHostApi.virtualStick"
        binaryMessenger:binaryMessenger
        codec:FLTDjiHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(virtualStickEnabled:pitch:roll:yaw:verticalThrottle:error:)], @"FLTDjiHostApi api (%@) doesn't respond to @selector(virtualStickEnabled:pitch:roll:yaw:verticalThrottle:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_enabled = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_pitch = GetNullableObjectAtIndex(args, 1);
        NSNumber *arg_roll = GetNullableObjectAtIndex(args, 2);
        NSNumber *arg_yaw = GetNullableObjectAtIndex(args, 3);
        NSNumber *arg_verticalThrottle = GetNullableObjectAtIndex(args, 4);
        FlutterError *error;
        [api virtualStickEnabled:arg_enabled pitch:arg_pitch roll:arg_roll yaw:arg_yaw verticalThrottle:arg_verticalThrottle error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.DjiHostApi.gimbalRotatePitch"
        binaryMessenger:binaryMessenger
        codec:FLTDjiHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(gimbalRotatePitchDegrees:error:)], @"FLTDjiHostApi api (%@) doesn't respond to @selector(gimbalRotatePitchDegrees:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_degrees = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api gimbalRotatePitchDegrees:arg_degrees error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.DjiHostApi.getMediaList"
        binaryMessenger:binaryMessenger
        codec:FLTDjiHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getMediaListWithError:)], @"FLTDjiHostApi api (%@) doesn't respond to @selector(getMediaListWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSArray<FLTMedia *> *output = [api getMediaListWithError:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.DjiHostApi.downloadMedia"
        binaryMessenger:binaryMessenger
        codec:FLTDjiHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(downloadMediaFileIndex:error:)], @"FLTDjiHostApi api (%@) doesn't respond to @selector(downloadMediaFileIndex:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_fileIndex = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        NSString *output = [api downloadMediaFileIndex:arg_fileIndex error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.DjiHostApi.deleteMedia"
        binaryMessenger:binaryMessenger
        codec:FLTDjiHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(deleteMediaFileIndex:error:)], @"FLTDjiHostApi api (%@) doesn't respond to @selector(deleteMediaFileIndex:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_fileIndex = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        NSNumber *output = [api deleteMediaFileIndex:arg_fileIndex error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.DjiHostApi.videoFeedStart"
        binaryMessenger:binaryMessenger
        codec:FLTDjiHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(videoFeedStartWithError:)], @"FLTDjiHostApi api (%@) doesn't respond to @selector(videoFeedStartWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api videoFeedStartWithError:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.DjiHostApi.videoFeedStop"
        binaryMessenger:binaryMessenger
        codec:FLTDjiHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(videoFeedStopWithError:)], @"FLTDjiHostApi api (%@) doesn't respond to @selector(videoFeedStopWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api videoFeedStopWithError:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.DjiHostApi.videoRecordStart"
        binaryMessenger:binaryMessenger
        codec:FLTDjiHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(videoRecordStartWithError:)], @"FLTDjiHostApi api (%@) doesn't respond to @selector(videoRecordStartWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api videoRecordStartWithError:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.DjiHostApi.videoRecordStop"
        binaryMessenger:binaryMessenger
        codec:FLTDjiHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(videoRecordStopWithError:)], @"FLTDjiHostApi api (%@) doesn't respond to @selector(videoRecordStopWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api videoRecordStopWithError:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface FLTDjiFlutterApiCodecReader : FlutterStandardReader
@end
@implementation FLTDjiFlutterApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [FLTDrone fromMap:[self readValue]];
    
    case 129:     
      return [FLTStream fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface FLTDjiFlutterApiCodecWriter : FlutterStandardWriter
@end
@implementation FLTDjiFlutterApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[FLTDrone class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
  if ([value isKindOfClass:[FLTStream class]]) {
    [self writeByte:129];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface FLTDjiFlutterApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FLTDjiFlutterApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FLTDjiFlutterApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FLTDjiFlutterApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FLTDjiFlutterApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    FLTDjiFlutterApiCodecReaderWriter *readerWriter = [[FLTDjiFlutterApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


@interface FLTDjiFlutterApi ()
@property (nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@end

@implementation FLTDjiFlutterApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  self = [super init];
  if (self) {
    _binaryMessenger = binaryMessenger;
  }
  return self;
}
- (void)setStatusDrone:(FLTDrone *)arg_drone completion:(void(^)(NSError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.DjiFlutterApi.setStatus"
      binaryMessenger:self.binaryMessenger
      codec:FLTDjiFlutterApiGetCodec()];
  [channel sendMessage:@[arg_drone ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
- (void)sendVideoStream:(FLTStream *)arg_stream completion:(void(^)(NSError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.DjiFlutterApi.sendVideo"
      binaryMessenger:self.binaryMessenger
      codec:FLTDjiFlutterApiGetCodec()];
  [channel sendMessage:@[arg_stream ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
@end
